'use client';

import React from 'react';
import { useStadiumState } from '../../../../context/StadiumStateContext';
import { DashboardLayout } from '../../../../components/organisms/DashboardLayout';
import { OperationsSidebar } from '../../../../components/organisms/OperationsSidebar';
import { DecisionBrief } from '../../../../components/organisms/DecisionBrief';
import { Button } from '../../../../components/atoms/Button';
import { Activity, Clock, RefreshCw } from 'lucide-react';
import { IconWrapper } from '../../../../components/atoms/IconWrapper';

export default function OperationsDecisions() {
  const {
    decisionHistory,
    isGeneratingDecision,
    isTriggeringScenario,
    requestDecision
  } = useStadiumState();

  const handleGlobalScan = () => {
    requestDecision('periodic-scan', 'global', 'Manual live feed refresh scan');
  };

  const latestDecisions = decisionHistory.slice(0, 5); // top 5 most recent

  return (
    <DashboardLayout sidebar={<OperationsSidebar />}>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-black tracking-tight text-text-primary uppercase flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-primary-500 animate-pulse" />
            Live Decision Feed
          </h1>
          <p className="text-xs text-text-muted mt-0.5">
            Real-time feed of recommendations generated by the AI reasoning agent.
          </p>
        </div>

        <Button
          variant="primary"
          size="sm"
          onClick={handleGlobalScan}
          disabled={isGeneratingDecision || isTriggeringScenario}
          className="font-bold text-xs"
        >
          {isGeneratingDecision ? (
            <>
              <IconWrapper icon={RefreshCw} size="sm" className="animate-spin mr-1.5" />
              Running Scan...
            </>
          ) : (
            <>
              <IconWrapper icon={Activity} size="sm" className="mr-1.5" />
              Trigger Global Scan
            </>
          )}
        </Button>
      </div>

      {/* Live Feed Body */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Main Feed Column */}
        <div className="lg:col-span-2 space-y-6">
          <h2 className="text-xs font-bold uppercase tracking-widest text-zinc-400">
            Real-Time Activity Feed
          </h2>

          {latestDecisions.length === 0 ? (
            <div className="flex flex-col items-center justify-center text-center p-12 rounded-3xl border border-zinc-800 bg-zinc-900/20 py-24">
              <div className="h-10 w-10 rounded-2xl bg-zinc-950/60 text-zinc-500 flex items-center justify-center mb-4 animate-pulse border border-zinc-850">
                <IconWrapper icon={Activity} size="sm" />
              </div>
              <h3 className="text-sm font-bold text-zinc-200">Awaiting AI recommendations</h3>
              <p className="text-xs text-zinc-500 mt-1 max-w-xs">
                No decisions have been generated in this session yet. Run a global scan or trigger a scenario simulation to start.
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              {latestDecisions.map((brief, idx) => (
                <div key={brief.id} className="relative">
                  {idx === 0 && (
                    <span className="absolute -left-2 top-4 flex h-3.5 w-3.5 items-center justify-center">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary-400 opacity-75" />
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-primary-500" />
                    </span>
                  )}
                  <DecisionBrief
                    brief={brief}
                    audienceOverride="operations"
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Right Info Column */}
        <div className="space-y-6">
          
          {/* Feed stats / Info Box */}
          <div className="p-6 rounded-3xl bg-zinc-900 border border-zinc-800 text-zinc-100 space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400">Operational Log Feed</h3>
            <p className="text-xs text-zinc-400 leading-relaxed">
              This feed shows recommendations in real time as mutations or scans run. Auto-polling synchronizes updates every 30 seconds.
            </p>
            <div className="flex items-center gap-2 text-[10px] text-zinc-500 font-mono">
              <IconWrapper icon={Clock} size="sm" />
              <span>Polling frequency: 30s</span>
            </div>
          </div>

          {/* Action checklist */}
          <div className="p-6 rounded-3xl bg-zinc-900 border border-zinc-800 text-zinc-100 space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400">Response Protocol</h3>
            <ul className="space-y-2 text-xs text-zinc-400">
              <li className="flex gap-2">
                <span className="font-bold text-zinc-300 font-mono">1.</span>
                <span>Evaluate confidence level tier before issuing gate adjustments.</span>
              </li>
              <li className="flex gap-2">
                <span className="font-bold text-zinc-300 font-mono">2.</span>
                <span>Coordinate with on-zone volunteers before dispatching resources.</span>
              </li>
              <li className="flex gap-2">
                <span className="font-bold text-zinc-300 font-mono">3.</span>
                <span>Ensure transport general advisory is updated if queue patterns shift.</span>
              </li>
            </ul>
          </div>

        </div>

      </div>
    </DashboardLayout>
  );
}
